# Generated by Django 4.1.4 on 2022-12-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=225)),
                ('total_plots', models.IntegerField()),
                ('plots_sold', models.IntegerField()),
                ('plots_available', models.IntegerField()),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('landmarks', models.CharField(max_length=225)),
                ('estate_features', models.CharField(max_length=225)),
                ('title', models.CharField(max_length=225)),
                ('initial_deposit', models.IntegerField()),
                ('promo', models.CharField(max_length=225)),
                ('owner', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='PlotSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('price_per_plot', models.IntegerField()),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.land')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.IntegerField()),
                ('development', models.IntegerField()),
                ('legal_document', models.IntegerField()),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.land')),
            ],
        ),
    ]
