# Generated by Django 4.1.4 on 2022-12-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_alter_land_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='estate_features',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='promo',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
