# Generated by Django 4.1.4 on 2022-12-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0005_rename_fees_fee_rename_images_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='estate_features',
        ),
        migrations.CreateModel(
            name='EstateFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_feature', models.CharField(max_length=225)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.land')),
            ],
        ),
    ]
