# Generated by Django 4.1.4 on 2022-12-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0007_remove_estatefeature_land_remove_fee_land_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotsize',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
