# Generated by Django 4.1.4 on 2022-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0008_alter_plotsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='estate_features',
            field=models.ManyToManyField(blank=True, null=True, related_name='land_estate_features', to='lands.estatefeature'),
        ),
        migrations.AlterField(
            model_name='land',
            name='fees',
            field=models.ManyToManyField(blank=True, null=True, related_name='land_fees', to='lands.fee'),
        ),
        migrations.AlterField(
            model_name='land',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='land_images', to='lands.image'),
        ),
        migrations.AlterField(
            model_name='land',
            name='landmarks',
            field=models.ManyToManyField(blank=True, null=True, related_name='land_landmarks', to='lands.landmark'),
        ),
        migrations.AlterField(
            model_name='land',
            name='plot_sizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='land_plot_sizes', to='lands.plotsize'),
        ),
    ]
